title: Helloworld
author: Zhenchen
email: 
description: > # this means to ignore newlines until "baseurl:"
  Hello this free computer world! I'm glad you to watch my first blog although there are still some mistakes in it.

# social links
hupu_username: SAS22nd # DO NOT include the @ character, or else the build will fail!
github_username: Zhenchen0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
